### PR TITLE
[Implements #93] Enable common preview tools for resources

### PR DESCRIPTION
**Pull request by abulojoshua1**
### What does the PR do
- Documents what resource views are and steps taken to enable some common resource views

### Changes Made
- Update to the README.md file

## Related Issue
[issue #93](https://github.com/geosolutions-it/ckanext-faoclh/issues/93)

### CODE REVIEW

**Comment by etj** [comment]
I created a wiki page with the very long explanation in the original PR:
   https://github.com/geosolutions-it/ckanext-faoclh/wiki/Enabling-Common-Resource-Preview-Tools

In the README file we only want installation and configuration info, not the whole rationale.

**Comment by abulojoshua1** [comment]
@etj, I've pushed new info with a summary of the installation and configuration info.

**Comment by etj** [comment]
> @etj, I've pushed new info with a summary of the installation and configuration info.

@abulojoshua1 pls stop pushing to this PR, I'm working on it and I already applied extensive changes.

**Comment by etj** [comment]
This PR has been replaced by commit 9cb6b5ab1d77e6de90433a5a31755280e8d8ba11

Original PR text is in https://github.com/geosolutions-it/ckanext-faoclh/wiki/Enabling-Common-Resource-Preview-Tools

**Pull request closed without merging**
