### PR TITLE
[Fixes #90] Custom Vocabularies Names are not translated

### LINKED ISSUE #90: Custom Vocabularies Names are not translated
We have to translate the custom vocabularies names in the required languages. In facets now only keys are appearing

2020_06_26_13_00_01_Tools_for_modelling_efficient_agriculture_practices_ES_Conjuntos_de_datos_

2020_06_26_13_00_54_Conjuntos_de_datos_CKAN

I think it could be easily done via i18n translations files. what do you think @etj ?

### PR DESCRIPTION
**Pull request by abulojoshua1**
Expected Behaviour
--------------------
The custom vocabularies have to be translated when there is a change in locales

What does the Fix:
------------------
- This pull request translates custom vocabularies to the required languages (English, Español, Français)

Changes Made
---------------
- I created and compiled .po files for all the required languages

Related Issue
-------------
[issue #90](https://github.com/geosolutions-it/ckanext-faoclh/issues/90)

### CODE REVIEW

**Comment by abulojoshua1** [comment]
> Why are all the localized strings duplicated in both ckan.po and ckanext-faoclh.po?

@etj, I was unsure of what the content of ckan.po should be and I thought of it as the default, but just now, I real translations can still be done when it is empty. Should I keep it empty or delete it?

**Comment by tdipisa** [comment]
@etj correct me if I'm wrong but, if I remember correctly, only the extension translation files should be present here and not ckan.po/mo. Isn't it?

**Comment by etj** [comment]
@tdipisa We were using the ckan.po files to override the "groups" -> "topics" translations

**Comment by etj** [comment]
@tdipisa @abulojoshua1 

give  a look to the original `ckan.po` files in ckanext-faoclh extension:
   https://github.com/geosolutions-it/ckanext-faoclh/blob/v1.0/ckanext/faoclh/i18n/en/LC_MESSAGES/ckan.po

- `ckan.po`: overrides of the translations of the base CKAN GUI
- `ckanext-faoclh.po`: translations of the strings originated in the ckanext-faoclh extension.

**Comment by etj** [comment]
@abulojoshua1 

https://www.google.com/search?q=python+po+file+translation

One of the first pages reports:
- POT – Portable Object Template. This is the file that you get when you extract texts from the application. Normally, you send this file to your translators.
- PO – Portable Object. This is the file that you receive back from the translators. It’s a text file that includes the original texts and the translations.
- MO – Machine Object. The MO file includes the exact same contents as PO file. The two files differ in their format. While a PO file is a text file and is easy for humans to read, MO files are compiled and are easy for computers to read. Your web server will use the MO file to display the translations.

The defaults are in the `.pot` file.

**Comment by abulojoshua1** [comment]
@etj, thanks for the info.

**Pull request merged**
